<?php 

$GLOBALS['SITE'] = "WWW";
$GLOBALS['site'] = $GLOBALS['SITE']; // HOLD OVER UNTIL WE FIND REMAINING LITTLE CASE 'site'
$GLOBALS[$SITE]['SYS_SLUG'] = "WWW";
$GLOBALS[$SITE]['SYS_DISPLAY'] = "WWW DEMO";
$GLOBALS[$SITE]['SYS'] = $GLOBALS[$SITE]['SYS_SLUG'];
$GLOBALS[$SITE]['URI'] = "DEMO/WWW";

// 

?>