<?php 

$GLOBALS['SITE'] = "DEMO/SKYLINE";
$GLOBALS['site'] = $GLOBALS['SITE']; // HOLD OVER UNTIL WE FIND REMAINING LITTLE CASE 'site'
$GLOBALS[$SITE]['SYS_SLUG'] = "SKYLINE";
$GLOBALS[$SITE]['SYS_DISPLAY'] = "SKYLINE(Demo)";
$GLOBALS[$SITE]['SYS'] = $GLOBALS[$SITE]['SYS_SLUG'];
$GLOBALS[$SITE]['URI'] = "DEMO/SKYLINE";

// 

?>